name: Refresh stars and regenerate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: halostatue/starlist@v1.0.0
        with:
          token: ${{ secrets.API_TOKEN }}
          git_email: ${{ secrets.USER_EMAIL }}
          git_name: ${{ github.repository_owner }}
